// Generated by CoffeeScript 1.4.0

/*
  HELPER FUNCTIONS TO MAP FROM SIMPLE GUI
*/


(function() {
  var random, simplegui, simplesound;

  random = (function() {

    function random() {}

    random.randrange = function(min, max) {
      return Math.floor(Math.random() * (max - min + 1)) + min;
    };

    random.random = function() {
      return Math.random();
    };

    return random;

  })();

  window.random = random;

  window.str = function(obj) {
    return obj.toString();
  };

  window.len = function(obj) {
    return obj.length;
  };

  window.Number.prototype.mod = function(n) {
    return ((this % n) + n) % n;
  };

  window.Array.prototype.remove = function(item) {
    var i, _i, _ref, _results;
    _results = [];
    for (i = _i = 0, _ref = this.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (this[i] === item) {
        this.splice(i, 1);
        break;
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  window.Array.prototype.difference_update = function(t) {
    var e, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = t.length; _i < _len; _i++) {
      e = t[_i];
      _results.push(this.remove(e));
    }
    return _results;
  };

  simplesound = (function() {

    function simplesound() {}

    simplesound.prototype.set_volume = function(new_volume) {};

    simplesound.prototype.rewind = function() {};

    simplesound.prototype.play = function() {};

    simplesound.prototype.pause = function() {};

    return simplesound;

  })();

  simplegui = (function() {

    function simplegui() {}

    simplegui.load_image = function(url, onload_cb) {
      var imageObj;
      imageObj = new Image();
      imageObj.onload = onload_cb;
      imageObj.src = url;
      return imageObj;
    };

    simplegui.draw_image = function(context, img, source_pos, source_size, dest_pos, dest_size, rotate) {
      var cpx, cpy, hdh, hdw, spx, spy;
      if (rotate == null) {
        rotate = 0;
      }
      context.save();
      hdw = Math.floor(dest_size[0] / 2);
      hdh = Math.floor(dest_size[1] / 2);
      cpx = dest_pos[0] - hdw;
      cpy = dest_pos[1] - hdh;
      spx = source_pos[0] - source_size[0] / 2;
      spy = source_pos[1] - source_size[1] / 2;
      context.translate(cpx, cpy);
      context.translate(hdw, hdh);
      context.rotate(rotate);
      context.translate(-cpx, -cpy);
      context.translate(-hdw, -hdh);
      context.drawImage(img, spx, spy, source_size[0], source_size[1], cpx, cpy, dest_size[0], dest_size[1]);
      return context.restore();
    };

    simplegui.draw_text = function(context, text, point, font_size, font_color) {
      context.font = "normal " + font_size + "px Verdana";
      context.fillStyle = font_color;
      return context.fillText(text, point[0], point[1]);
    };

    simplegui.load_sound = function(url, onload_cb) {
      return new simplesound();
    };

    simplegui.KEY_MAP = {
      'left': 37,
      'right': 39,
      'up': 38,
      'space': 32
    };

    return simplegui;

  })();

  window.simplegui = simplegui;

  /*
    END HELPER FUNCTIONS
  */


}).call(this);
